# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pro.xdc

# IP: ip/Uart_Ram_VGA/Uart_Ram_VGA.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Uart_Ram_VGA || ORIG_REF_NAME==Uart_Ram_VGA} -quiet] -quiet
